// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpgTK3atRqmXq-64fPt_lvfDoHteNn5o',
    appId: '1:677889739488:android:d1cf967e1a4ce6a2ea1e85',
    messagingSenderId: '677889739488',
    projectId: 'death-notes-786',
    storageBucket: 'death-notes-786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCirpF5-AmhfVLDjgHPvaWNmElQBXfT3hM',
    appId: '1:677889739488:ios:85a1b3a9b2a5960dea1e85',
    messagingSenderId: '677889739488',
    projectId: 'death-notes-786',
    storageBucket: 'death-notes-786.firebasestorage.app',
    iosBundleId: 'com.example.deathNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCirpF5-AmhfVLDjgHPvaWNmElQBXfT3hM',
    appId: '1:677889739488:ios:85a1b3a9b2a5960dea1e85',
    messagingSenderId: '677889739488',
    projectId: 'death-notes-786',
    storageBucket: 'death-notes-786.firebasestorage.app',
    iosBundleId: 'com.example.deathNotes',
  );
}
